### PR TITLE
Adding Cheatsheet for R language 

### PR DESCRIPTION
**Pull request by alpha-k911**
Adding Cheatsheet for the R language, added lists operations and Dataframe creation operations

### CODE REVIEW

**Comment by alpha-k911** [comment]
@AnuragAnalog add  "hacktoberfest" and "hacktoberfest-accepted" labels and Merge the PR

**Review by AnuragAnalog — APPROVED** [review]
Good, hacktoberfest topic neenu add cheyyali raaa 😅😂

**Comment by AnuragAnalog** [comment]
@alpha-k911 add chesanu le label don't worry

**Comment by alpha-k911** [comment]
Yeah, i just forgot

**Pull request merged**
